### PR TITLE
made method public

### PR DESCRIPTION
**Pull request by falkorichter**
## Description of changes
In case of catastropic failure of VGS services we would like to use the VGS collect SDK and tokenise with another service. 

## Example

```kotlin
private lateinit var vgsCollect: VGSCollect

val request: VGSRequest =
    VGSRequest.VGSRequestBuilder().setMethod(HTTPMethod.POST).setPath(VGS_PATH).build()

vgsCollect.collectUserData(
    request,
    { values ->
        backupTokenizationService
            .tokenize(values)
            .subscribe(
                {
                    // tokenization complete
                },
                { error ->
                    Log.e(
                        "alternative tokenization",
                        "could not tokenize card ${error.localizedMessage}"
                    )
                },
            )
    }
)

```

### CODE REVIEW

**Comment by DmytroDm** [comment]
@falkorichter There is a response listener `VgsCollectResponseListener` that you can use to determine if the tokenization request fails. You can use it like:
```
collect?.addOnResponseListeners(object : VgsCollectResponseListener {

    override fun onResponse(response: VGSResponse?) {
        if (response is VGSResponse.ErrorResponse) {
            Log.e(
                "alternative tokenization",
                "could not tokenize card ${response.localizeMessage}"
            )
        }
    }
})
```

**Comment by DmytroDm** [comment]
@falkorichter Hi, by making `collectUserData` public we expose user-sensitive data(`values`), so this is not secure or PCI compliant.

**Comment by falkorichter** [comment]
> @falkorichter Hi, by making `collectUserData` public we expose user-sensitive data(`values`), so this is not secure or PCI compliant.

I see your line of argumentation. Since the data is unencrypted in memory, I would argue the data is already exposed. This project is open source and everything is exposed. 

Where is the technical definition of "Exposure" in the PCI context you are referring to? I've worked with card terminals before and we were forced to never keep the CVV in memory of the device, we sent over keystrokes to the server. This was a way at the time to ensure the user-sensitive data was not exposed. In this context, the host application is a trust anchor, there is no additional trust lost if we make that method public.

**Comment by DmytroDm** [comment]
@falkorichter We don't store raw data on the device, we gather raw data in the app -> send it to our proxy -> return encrypted data back to the app(I guess something similar to what you did for card terminals), so the customer app can use only alias/token and not the user-sensitive data.

In our case "Exposure" means that the customer app has direct access to the user-sensitive data, which means the customer app will need more time to become PCI compliant.

**Pull request closed without merging**
